### ISSUE TITLE
zf2 config package not available anymore

### ISSUE THREAD

**Issue by sharpner** [zendframework/ZF2Package#20]
Hi, 
we got the following problem installing dependencies.

 [Composer\Downloader\TransportException]  
The "https://packages.zendframework.com/composer/Zend_Config-2.0.8.zip" file could not be downloaded (HTTP/1.1 404 Not Found)  

did the download path change but not the dist url?

Thanks in advance

**Comment by weierophinney** [comment]
Run a composer update; we changed the Composer repository structure around
4 months ago (going from hand-rolled to straight Satis), which necessitated
new package names. Rewrites were untenable to implement, unfortunately.

On Friday, July 12, 2013, Nino wrote:

> Hi,
> we got the following problem installing dependencies.
> 
> [Composer\Downloader\TransportException]
> 
> The "https://packages.zendframework.com/composer/Zend_Config-2.0.8.zip"
> file could not be downloaded (HTTP/1.1 404 Not Found)
> 
> did the download path change but not the dist url?
> 
> Thanks in advance
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/zendframework/ZF2Package/issues/20
> .

## 

Matthew Weier O'Phinney
matthew@weierophinney.net
http://mwop.net/
