### ISSUE TITLE
zf2 package for skeleton-application

### ISSUE THREAD

**Issue by ghost** [zendframework/ZF2Package#23]
hi!

I noticed that there is no 2.4.x package for the skeleton-application (https://github.com/zendframework/ZendSkeletonApplication) on
https://packages.zendframework.com/

Is this planned in the near future?

Thanks in advance

**Comment by Maks3w** [comment]
You should ask this in the skeleton issue tracker first.

**Comment by ghost** [comment]
ok, I thought I did it already :)
https://github.com/zendframework/ZendSkeletonApplication/pull/281#issuecomment-112457281

But anyway:
https://github.com/zendframework/ZendSkeletonApplication/issues/294

Thanks!

**Comment by Maks3w** [comment]
Sorry I didn't check the tag don't exists.
